export const AreaType = {
  POLYGON: 'POLYGON',
  CIRCLE: 'CIRCLE',
};

export const LayerTypes = {
  UNITS_LAYER: 'UNITS_LAYER',
  ROUTE_HISTORY_LAYER: 'ROUTE_HISTORY_LAYER',
  MEASURE_LAYER: 'MEASURE_LAYER',
  BASE_LAYER: 'BASE_LAYER',
  AREA_LAYER: 'AREA_LAYER',
  DRAW_AREA_LAYER: 'DRAW_AREA_LAYER',
  NOTIFICATION_LAYER: 'NOTIFICATION_LAYER',
  HUMAN_LAYER: 'HUMAN_LAYER',
};

export const DrawTypes = {
  NONE: 'NONE',
  MEASURE: 'MEASURE',
  AREA_CIRCLE: 'AREA_CIRCLE',
  AREA_POLYGON: 'AREA_POLYGON',
  EDIT_AREA_CIRCLE: 'EDIT_AREA_CIRCLE',
  EDIT_AREA_POLYGON: 'EDIT_AREA_POLYGON',
  TEMP_AREA_DRAW: 'TEMP_AREA_DRAW',
};

export const FeatureTypes = {
  UNIT: 'UNIT',
  ROUTE_HISTORY: 'ROUTE_HISTORY',
  AREA: 'AREA',
  MEASURE: 'MEASURE',
  NOTIFICATION: 'NOTIFICATION',
  HUMAN: 'HUMAN',
};

export const HumanTypes = {
  VICTIM: 'VICTIM',
  OFFENDER: 'OFFENDER',
};

export const RouteIconTypes = {
  ROUTE: 'ROUTE',
  ROUTE_START: 'ROUTE_START',
  ROUTE_END: 'ROUTE_END',
  HUMAN_VICTIM: 'HUMAN_VICTIM',
  HUMAN_OFFENDER: 'HUMAN_OFFENDER',
};
